name = "NytePack"
author = "RedAngel121"
version = "1.02"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53c14123a6abafa8c0f166178b056cf4b9467ec0fbd387df9b71e30bd32456b7"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
