name = "NytePack"
author = "RedAngel121"
version = "1.02"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d62c7c46a71ff77e54d65d57c3560c742d6a52570aa64dec5c4566bffe15b21"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
