name = "NytePack"
author = "RedAngel121"
version = "1.02"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c68e316dc509a672d0df60ff54bcdc42038f64f7479edc6ba5d6b3613c1a44fa"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
