name = "NytePack"
author = "RedAngel121"
version = "1.02"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e21616fa11fd6b0fd8e5c66454c0d07535fbbc3a0f39166a5f9bdcd46da27283"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
